name: Process Trackers

on:
  schedule:
    - cron: '0 12 * * *'  # 每天UTC时间12点自动运行
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create directories
      run: mkdir -p data src

    - name: Download trackers
      run: |
        declare -A files=(
          ["https"]="trackers_all_https.txt"
          ["i2p"]="trackers_all_i2p.txt"
          ["udp"]="trackers_all_udp.txt"
          ["ws"]="trackers_all_ws.txt"
          ["best_ip"]="trackers_best_ip.txt"
        )
        for key in "${!files[@]}"; do
          url="https://raw.githubusercontent.com/ngosang/trackerslist/master/${files[$key]}"
          echo "Downloading: $url"
          curl -sfL --retry 3 --connect-timeout 15 -o "data/${files[$key]}" "$url"
          if [[ ! -s "data/${files[$key]}" ]]; then
            echo "Warning: Failed to download or file is empty: ${files[$key]}"
          fi
        done

    - name: Commit raw data  # 第一次提交：仅原始数据
      uses: EndBug/add-and-commit@v9
      with:
        add: 'data/*.txt'
        commit_message: 'Auto-Update Raw Trackers (UTC: $(date -u +"%Y-%m-%dT%H:%M:%S"))'
        signoff: true
        skip_empty: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq --no-install-recommends grep sed coreutils
        [ -x src/process.sh ] || chmod +x src/process.sh

    - name: Process data
      run: |
        input_files=$(find data -name '*.txt' -size +0c -print0 | xargs -0)
        if [[ -z "$input_files" ]]; then
          echo "Error: No valid input files found."
          exit 1
        fi
        ./src/process.sh -i "$input_files" -o processed.txt
        [ -s processed.txt ] || exit 1

    - name: Commit processed result  # 第二次提交：处理结果
      uses: EndBug/add-and-commit@v9
      with:
        add: 'processed.txt'
        commit_message: 'Auto-Update Processed Trackers (UTC: $(date -u +"%Y-%m-%dT%H:%M:%S"))'
        signoff: true
        skip_empty: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
