name: Process Trackers

on:
  schedule:
    - cron: '0 12 * * *'  # 每天UTC时间12点自动运行
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create directories
      run: mkdir -p data src

    - name: Download trackers
      run: |
        declare -A files=(
          ["https"]="trackers_all_https.txt"
          ["i2p"]="trackers_all_i2p.txt"
          ["udp"]="trackers_all_udp.txt"
          ["ws"]="trackers_all_ws.txt"
          ["best_ip"]="trackers_best_ip.txt"
        )
        for key in "${!files[@]}"; do
          url="https://raw.githubusercontent.com/ngosang/trackerslist/master/${files[$key]}"
          echo "Downloading: $url"
          curl -sfL --retry 3 --connect-timeout 15 -o "data/${files[$key]}" "$url"
          if [[ ! -s "data/${files[$key]}" ]]; then
            echo "Warning: Failed to download or file is empty: ${files[$key]}"
          fi
        done

    - name: Commit raw data
      uses: EndBug/add-and-commit@v9
      with:
        add: 'data/*.txt'
        message: 'Auto-Update Raw Trackers (UTC: $(date -u +"%Y-%m-%dT%H:%M:%S"))'  # 修正参数名
        # 移除非法的 signoff 和 skip_empty 参数
        # 通过 git config 添加签名
        commit: "--signoff --allow-empty"  # 新版本使用 commit 参数传递 git 选项
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq --no-install-recommends grep sed coreutils
        [ -x src/process.sh ] || chmod +x src/process.sh
    
    - name: Process data
      run: |
        input_files=()
        while IFS= read -r -d $'\0' file; do
            input_files+=("$file")
        done < <(find data -name '*.txt' -size +0c -print0)
    
        if [[ ${#input_files[@]} -eq 0 ]]; then
            echo "Error: No valid input files found."
            exit 1
        fi
    
        # 构建参数数组，每个文件单独添加 -i 参数
        args=()
        for file in "${input_files[@]}"; do
            args+=(-i "$file")
        done
        ./src/process.sh "${args[@]}" -o processed.txt
        [ -s processed.txt ] || exit 1

    - name: Commit processed result
      uses: EndBug/add-and-commit@v9
      with:
        add: 'processed.txt'
        message: 'Auto-Update Processed Trackers (UTC: $(date -u +"%Y-%m-%dT%H:%M:%S"))'  # 修正参数名
        commit: "--signoff --allow-empty"  # 合并签名和空提交选项
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
