name: Process Trackers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create data directory
      run: mkdir -p data

    - name: Download tracker files
      run: |
        curl -o data/trackers_all_https.txt https://example.com/trackers_all_https.txt
        curl -o data/trackers_all_i2p.txt https://example.com/trackers_all_i2p.txt
        curl -o data/trackers_all_udp.txt https://example.com/trackers_all_udp.txt
        curl -o data/trackers_all_ws.txt https://example.com/trackers_all_ws.txt
        curl -o data/trackers_best_ip.txt https://example.com/trackers_best_ip.txt

    - name: Make process.sh executable
      run: chmod +x src/process.sh

    - name: Run process script
      run: ./src/process.sh -i "data/*.txt" -o processed.txt

    - name: Push Update
      uses: EndBug/add-and-commit@v9
      with:
        add: 'processed.txt'
        message: 'Auto Update Trackers'
